name: '${project.name}'
version: '${project.version}'
main: xyz.coffeeisle.welcomemat.WelcomeMat
api-version: '1.13'
folia-supported: true
authors: [angeldev0]
softdepend: [PlaceholderAPI]
description: A simple welcome plugin.
commands:
  welcomemat:
    description: Main command for WelcomeMat plugin
    usage: /<command> [reload|test]
    aliases: [wm]
permissions:
  welcomemat.reload:
    description: Allows reloading the plugin configuration
    default: op
  welcomemat.test:
    description: Allows testing welcome messages
    default: op
